language: ruby
sudo: required
dist: trusty
group: deprecated-2017Q2
rvm:
  - 2.4.1
  - 2.3.3
  - jruby-9.1.12.0
gemfile:
  - Gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom
  # matrix:
  #   - WINDOW_TEST=true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
      - awesome

matrix:
  include:
    - gemfile: gemfiles/Gemfile.rspec-34
      rvm: 2.3.3
      env: CAPYBARA_FF=true
      addons:
        firefox: latest
        apt:
          packages:
            - awesome
    - gemfile: Gemfile
      rvm: 2.4.1
      env: HEADLESS=true
    - gemfile: gemfiles/Gemfile.beta-versions
      rvm: 2.3.3
      env: CAPYBARA_FF=true
      addons:
        firefox: latest-beta
        apt:
          packages:
            - awesome
    - gemfile: gemfiles/Gemfile.edge-marionette
      rvm: 2.3.3
      env: CAPYBARA_FF=true
      addons:
        firefox: latest-nightly
        apt:
          packages:
            - awesome
    - gemfile: Gemfile
      rvm: 2.4.1
      env: CAPYBARA_FF=true HEADLESS=true
      addons:
        firefox: latest-nightly
  allow_failures:
    - gemfile: gemfiles/Gemfile.beta-versions
    - gemfile: gemfiles/Gemfile.edge-marionette
    - rvm: rbx-3
    - rvm: jruby-9.1.12.0
    - gemfile: Gemfile
      rvm: 2.4.1
      env: CAPYBARA_FF=true HEADLESS=true
    - env: HEADLESS=true
before_install:
  - mkdir -p ~/drivers; export PATH=~/drivers:$PATH;
  - CHROMEDRIVER_VERSION=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE);
    CHROMEDRIVER_URL="http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip";
    FILE=`mktemp`; wget "$CHROMEDRIVER_URL" -qO $FILE && unzip $FILE chromedriver -d ~/drivers; rm $FILE; chmod 777 ~/drivers/chromedriver;
    ~/drivers/chromedriver --version;
  - GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz";
    FILE=`mktemp`; wget "$GECKODRIVER_URL" -qO $FILE && tar xz -C ~/drivers -f $FILE geckodriver; rm $FILE; chmod 777 ~/drivers/geckodriver;
    ~/drivers/geckodriver --version;
  - if [[ $BUNDLE_GEMFILE =~ Gemfile.edge-marionette$ ]]; then
      pushd ..;
      git clone --depth 1 https://github.com/SeleniumHQ/selenium.git;
      cd selenium; ./go //rb:gem:build;
      popd;
      bundle config local.selenium-webdriver ../selenium/build/rb;
    fi
before_script:
  - if [[ -z $HEADLESS ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 1;
      mkdir -p ~/.config/awesome;
      echo "require('awful'); tags = {}; tags[1] = awful.tag({'name'})" > ~/.config/awesome/rc.lua;
      awesome &
    fi
script: "bundle exec rake travis"
